stages:
- stage: 'Deploy'
  jobs:
  - job: Deploy
    steps:
    - task: AzureResourceManagerTemplateDeployment@3.210.0
      inputs:
        deploymentScope: 'Management Group'
        azureResourceManagerConnection: 'Jonas - Dev/Test(0cd0b54d-1293-4ea8-a959-2f6d3e55a688)'
        location: 'West Europe'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Azure/Enterprise-Scale/main/eslzArm/managementGroupTemplates/policyDefinitions/policies.json'
        overrideParameters: '--topLevelManagementGroupPrefix "jonas-mgmt"'
        deploymentMode: 'Incremental'